import 'package:flutter/material.dart';
import 'dart:ui';
import 'package:tamagotchi/Screen/screen_colors.dart';
import 'package:tamagotchi/Screen/coordinate.dart';

Map<String, List<Coordinate>> alphabetCoords = {

  "0" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "1" : [Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "2" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "3" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "4" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "5" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "6" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "7" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "8" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "9" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],

  "a" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "b" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "c" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "e" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "f" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "g" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "h" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "i" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "j" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "k" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "l" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "m" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0)],
  "n" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0)],
  "o" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "p" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "q" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0)],
  "r" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "s" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "t" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "u" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "v" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "w" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0)],
  "x" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "y" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],
  "z" : [Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)],

  "A" : [Coordinate(0,9), Coordinate(1,9), Coordinate(2,9), Coordinate(3,9), Coordinate(4,9), Coordinate(5,9),
    Coordinate(0,8), Coordinate(1,8), Coordinate(2,8), Coordinate(3,8), Coordinate(4,8), Coordinate(5,8),
    Coordinate(0,7), Coordinate(1,7), Coordinate(2,7), Coordinate(3,7), Coordinate(4,7), Coordinate(5,7),
    Coordinate(0,6), Coordinate(1,6), Coordinate(2,6), Coordinate(3,6), Coordinate(4,6), Coordinate(5,6),
    Coordinate(0,5), Coordinate(1,5), Coordinate(2,5), Coordinate(3,5), Coordinate(4,5), Coordinate(5,5),
    Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(5,4),
    Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(5,3),
    Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(5,2),
    Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(5,1),
    Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0), Coordinate(5,0)],
  "B" : [Coordinate(0,9), Coordinate(1,9), Coordinate(2,9), Coordinate(3,9), Coordinate(4,9), Coordinate(5,9),
    Coordinate(0,8), Coordinate(1,8), Coordinate(2,8), Coordinate(3,8), Coordinate(4,8), Coordinate(5,8),
    Coordinate(0,7), Coordinate(1,7), Coordinate(2,7), Coordinate(3,7), Coordinate(4,7), Coordinate(5,7),
    Coordinate(0,6), Coordinate(1,6), Coordinate(2,6), Coordinate(3,6), Coordinate(4,6), Coordinate(5,6),
    Coordinate(0,5), Coordinate(1,5), Coordinate(2,5), Coordinate(3,5), Coordinate(4,5), Coordinate(5,5),
    Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(5,4),
    Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(5,3),
    Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(5,2),
    Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(5,1),
    Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0), Coordinate(5,0)],
  "C" : [Coordinate(0,9), Coordinate(1,9), Coordinate(2,9), Coordinate(3,9), Coordinate(4,9), Coordinate(5,9),
    Coordinate(0,8), Coordinate(1,8), Coordinate(2,8), Coordinate(3,8), Coordinate(4,8), Coordinate(5,8),
    Coordinate(0,7), Coordinate(1,7), Coordinate(2,7), Coordinate(3,7), Coordinate(4,7), Coordinate(5,7),
    Coordinate(0,6), Coordinate(1,6), Coordinate(2,6), Coordinate(3,6), Coordinate(4,6), Coordinate(5,6),
    Coordinate(0,5), Coordinate(1,5), Coordinate(2,5), Coordinate(3,5), Coordinate(4,5), Coordinate(5,5),
    Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(5,4),
    Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(5,3),
    Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(5,2),
    Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(5,1),
    Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0), Coordinate(5,0)],
  "D" : [Coordinate(0,9), Coordinate(1,9), Coordinate(2,9), Coordinate(3,9), Coordinate(4,9), Coordinate(5,9),
    Coordinate(0,8), Coordinate(1,8), Coordinate(2,8), Coordinate(3,8), Coordinate(4,8), Coordinate(5,8),
    Coordinate(0,7), Coordinate(1,7), Coordinate(2,7), Coordinate(3,7), Coordinate(4,7), Coordinate(5,7),
    Coordinate(0,6), Coordinate(1,6), Coordinate(2,6), Coordinate(3,6), Coordinate(4,6), Coordinate(5,6),
    Coordinate(0,5), Coordinate(1,5), Coordinate(2,5), Coordinate(3,5), Coordinate(4,5), Coordinate(5,5),
    Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(5,4),
    Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(5,3),
    Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(5,2),
    Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(5,1),
    Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0), Coordinate(5,0)],
  "E" : [Coordinate(0,9), Coordinate(1,9), Coordinate(2,9), Coordinate(3,9), Coordinate(4,9), Coordinate(5,9),
    Coordinate(0,8), Coordinate(1,8), Coordinate(2,8), Coordinate(3,8), Coordinate(4,8), Coordinate(5,8),
    Coordinate(0,7), Coordinate(1,7), Coordinate(2,7), Coordinate(3,7), Coordinate(4,7), Coordinate(5,7),
    Coordinate(0,6), Coordinate(1,6), Coordinate(2,6), Coordinate(3,6), Coordinate(4,6), Coordinate(5,6),
    Coordinate(0,5), Coordinate(1,5), Coordinate(2,5), Coordinate(3,5), Coordinate(4,5), Coordinate(5,5),
    Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(5,4),
    Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(5,3),
    Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(5,2),
    Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(5,1),
    Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0), Coordinate(5,0)],
  "F" : [Coordinate(0,9), Coordinate(1,9), Coordinate(2,9), Coordinate(3,9), Coordinate(4,9), Coordinate(5,9),
    Coordinate(0,8), Coordinate(1,8), Coordinate(2,8), Coordinate(3,8), Coordinate(4,8), Coordinate(5,8),
    Coordinate(0,7), Coordinate(1,7), Coordinate(2,7), Coordinate(3,7), Coordinate(4,7), Coordinate(5,7),
    Coordinate(0,6), Coordinate(1,6), Coordinate(2,6), Coordinate(3,6), Coordinate(4,6), Coordinate(5,6),
    Coordinate(0,5), Coordinate(1,5), Coordinate(2,5), Coordinate(3,5), Coordinate(4,5), Coordinate(5,5),
    Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(5,4),
    Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(5,3),
    Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(5,2),
    Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(5,1),
    Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0), Coordinate(5,0)],
  "G" : [Coordinate(0,9), Coordinate(1,9), Coordinate(2,9), Coordinate(3,9), Coordinate(4,9), Coordinate(5,9),
    Coordinate(0,8), Coordinate(1,8), Coordinate(2,8), Coordinate(3,8), Coordinate(4,8), Coordinate(5,8),
    Coordinate(0,7), Coordinate(1,7), Coordinate(2,7), Coordinate(3,7), Coordinate(4,7), Coordinate(5,7),
    Coordinate(0,6), Coordinate(1,6), Coordinate(2,6), Coordinate(3,6), Coordinate(4,6), Coordinate(5,6),
    Coordinate(0,5), Coordinate(1,5), Coordinate(2,5), Coordinate(3,5), Coordinate(4,5), Coordinate(5,5),
    Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(5,4),
    Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(5,3),
    Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(5,2),
    Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(5,1),
    Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0), Coordinate(5,0)],
  "H" : [Coordinate(0,9), Coordinate(1,9), Coordinate(2,9), Coordinate(3,9), Coordinate(4,9), Coordinate(5,9),
    Coordinate(0,8), Coordinate(1,8), Coordinate(2,8), Coordinate(3,8), Coordinate(4,8), Coordinate(5,8),
    Coordinate(0,7), Coordinate(1,7), Coordinate(2,7), Coordinate(3,7), Coordinate(4,7), Coordinate(5,7),
    Coordinate(0,6), Coordinate(1,6), Coordinate(2,6), Coordinate(3,6), Coordinate(4,6), Coordinate(5,6),
    Coordinate(0,5), Coordinate(1,5), Coordinate(2,5), Coordinate(3,5), Coordinate(4,5), Coordinate(5,5),
    Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(5,4),
    Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(5,3),
    Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(5,2),
    Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(5,1),
    Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0), Coordinate(5,0)],
  "I" : [Coordinate(0,9), Coordinate(1,9), Coordinate(2,9), Coordinate(3,9), Coordinate(4,9), Coordinate(5,9),
    Coordinate(0,8), Coordinate(1,8), Coordinate(2,8), Coordinate(3,8), Coordinate(4,8), Coordinate(5,8),
    Coordinate(0,7), Coordinate(1,7), Coordinate(2,7), Coordinate(3,7), Coordinate(4,7), Coordinate(5,7),
    Coordinate(0,6), Coordinate(1,6), Coordinate(2,6), Coordinate(3,6), Coordinate(4,6), Coordinate(5,6),
    Coordinate(0,5), Coordinate(1,5), Coordinate(2,5), Coordinate(3,5), Coordinate(4,5), Coordinate(5,5),
    Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(5,4),
    Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(5,3),
    Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(5,2),
    Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(5,1),
    Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0), Coordinate(5,0)],
  "J" : [Coordinate(0,9), Coordinate(1,9), Coordinate(2,9), Coordinate(3,9), Coordinate(4,9), Coordinate(5,9),
    Coordinate(0,8), Coordinate(1,8), Coordinate(2,8), Coordinate(3,8), Coordinate(4,8), Coordinate(5,8),
    Coordinate(0,7), Coordinate(1,7), Coordinate(2,7), Coordinate(3,7), Coordinate(4,7), Coordinate(5,7),
    Coordinate(0,6), Coordinate(1,6), Coordinate(2,6), Coordinate(3,6), Coordinate(4,6), Coordinate(5,6),
    Coordinate(0,5), Coordinate(1,5), Coordinate(2,5), Coordinate(3,5), Coordinate(4,5), Coordinate(5,5),
    Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(5,4),
    Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(5,3),
    Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(5,2),
    Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(5,1),
    Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0), Coordinate(5,0)],
  "K" : [Coordinate(0,9), Coordinate(1,9), Coordinate(2,9), Coordinate(3,9), Coordinate(4,9), Coordinate(5,9),
    Coordinate(0,8), Coordinate(1,8), Coordinate(2,8), Coordinate(3,8), Coordinate(4,8), Coordinate(5,8),
    Coordinate(0,7), Coordinate(1,7), Coordinate(2,7), Coordinate(3,7), Coordinate(4,7), Coordinate(5,7),
    Coordinate(0,6), Coordinate(1,6), Coordinate(2,6), Coordinate(3,6), Coordinate(4,6), Coordinate(5,6),
    Coordinate(0,5), Coordinate(1,5), Coordinate(2,5), Coordinate(3,5), Coordinate(4,5), Coordinate(5,5),
    Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(5,4),
    Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(5,3),
    Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(5,2),
    Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(5,1),
    Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0), Coordinate(5,0)],
  "L" : [Coordinate(0,9), Coordinate(1,9), Coordinate(2,9), Coordinate(3,9), Coordinate(4,9), Coordinate(5,9),
    Coordinate(0,8), Coordinate(1,8), Coordinate(2,8), Coordinate(3,8), Coordinate(4,8), Coordinate(5,8),
    Coordinate(0,7), Coordinate(1,7), Coordinate(2,7), Coordinate(3,7), Coordinate(4,7), Coordinate(5,7),
    Coordinate(0,6), Coordinate(1,6), Coordinate(2,6), Coordinate(3,6), Coordinate(4,6), Coordinate(5,6),
    Coordinate(0,5), Coordinate(1,5), Coordinate(2,5), Coordinate(3,5), Coordinate(4,5), Coordinate(5,5),
    Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(5,4),
    Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(5,3),
    Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(5,2),
    Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(5,1),
    Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0), Coordinate(5,0)],
  "M" : [Coordinate(0,9), Coordinate(1,9), Coordinate(2,9), Coordinate(3,9), Coordinate(4,9), Coordinate(5,9), Coordinate(6,9),
    Coordinate(0,8), Coordinate(1,8), Coordinate(2,8), Coordinate(3,8), Coordinate(4,8), Coordinate(5,8), Coordinate(6,8),
    Coordinate(0,7), Coordinate(1,7), Coordinate(2,7), Coordinate(3,7), Coordinate(4,7), Coordinate(5,7), Coordinate(6,7),
    Coordinate(0,6), Coordinate(1,6), Coordinate(2,6), Coordinate(3,6), Coordinate(4,6), Coordinate(5,6), Coordinate(6,6),
    Coordinate(0,5), Coordinate(1,5), Coordinate(2,5), Coordinate(3,5), Coordinate(4,5), Coordinate(5,5), Coordinate(6,5),
    Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(5,4), Coordinate(6,4),
    Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(5,3), Coordinate(6,3),
    Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(5,2), Coordinate(6,2),
    Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(5,1), Coordinate(6,1),
    Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0), Coordinate(5,0), Coordinate(6,0),],
  "N" : [Coordinate(0,9), Coordinate(1,9), Coordinate(2,9), Coordinate(3,9), Coordinate(4,9), Coordinate(5,9), Coordinate(6,9),
    Coordinate(0,8), Coordinate(1,8), Coordinate(2,8), Coordinate(3,8), Coordinate(4,8), Coordinate(5,8), Coordinate(6,8),
    Coordinate(0,7), Coordinate(1,7), Coordinate(2,7), Coordinate(3,7), Coordinate(4,7), Coordinate(5,7), Coordinate(6,7),
    Coordinate(0,6), Coordinate(1,6), Coordinate(2,6), Coordinate(3,6), Coordinate(4,6), Coordinate(5,6), Coordinate(6,6),
    Coordinate(0,5), Coordinate(1,5), Coordinate(2,5), Coordinate(3,5), Coordinate(4,5), Coordinate(5,5), Coordinate(6,5),
    Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(5,4), Coordinate(6,4),
    Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(5,3), Coordinate(6,3),
    Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(5,2), Coordinate(6,2),
    Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(5,1), Coordinate(6,1),
    Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0), Coordinate(5,0), Coordinate(6,0),],
  "O" : [Coordinate(0,9), Coordinate(1,9), Coordinate(2,9), Coordinate(3,9), Coordinate(4,9), Coordinate(5,9),
    Coordinate(0,8), Coordinate(1,8), Coordinate(2,8), Coordinate(3,8), Coordinate(4,8), Coordinate(5,8),
    Coordinate(0,7), Coordinate(1,7), Coordinate(2,7), Coordinate(3,7), Coordinate(4,7), Coordinate(5,7),
    Coordinate(0,6), Coordinate(1,6), Coordinate(2,6), Coordinate(3,6), Coordinate(4,6), Coordinate(5,6),
    Coordinate(0,5), Coordinate(1,5), Coordinate(2,5), Coordinate(3,5), Coordinate(4,5), Coordinate(5,5),
    Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(5,4),
    Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(5,3),
    Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(5,2),
    Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(5,1),
    Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0), Coordinate(5,0)],
  "P" : [Coordinate(0,9), Coordinate(1,9), Coordinate(2,9), Coordinate(3,9), Coordinate(4,9), Coordinate(5,9),
    Coordinate(0,8), Coordinate(1,8), Coordinate(2,8), Coordinate(3,8), Coordinate(4,8), Coordinate(5,8),
    Coordinate(0,7), Coordinate(1,7), Coordinate(2,7), Coordinate(3,7), Coordinate(4,7), Coordinate(5,7),
    Coordinate(0,6), Coordinate(1,6), Coordinate(2,6), Coordinate(3,6), Coordinate(4,6), Coordinate(5,6),
    Coordinate(0,5), Coordinate(1,5), Coordinate(2,5), Coordinate(3,5), Coordinate(4,5), Coordinate(5,5),
    Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(5,4),
    Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(5,3),
    Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(5,2),
    Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(5,1),
    Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0), Coordinate(5,0)],
  "Q" : [Coordinate(0,9), Coordinate(1,9), Coordinate(2,9), Coordinate(3,9), Coordinate(4,9), Coordinate(5,9),
    Coordinate(0,8), Coordinate(1,8), Coordinate(2,8), Coordinate(3,8), Coordinate(4,8), Coordinate(5,8),
    Coordinate(0,7), Coordinate(1,7), Coordinate(2,7), Coordinate(3,7), Coordinate(4,7), Coordinate(5,7),
    Coordinate(0,6), Coordinate(1,6), Coordinate(2,6), Coordinate(3,6), Coordinate(4,6), Coordinate(5,6),
    Coordinate(0,5), Coordinate(1,5), Coordinate(2,5), Coordinate(3,5), Coordinate(4,5), Coordinate(5,5),
    Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(5,4),
    Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(5,3),
    Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(5,2),
    Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(5,1),
    Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0), Coordinate(5,0), Coordinate(6,0),
    Coordinate(5,-1), Coordinate(6,-1)],
  "R" : [Coordinate(0,9), Coordinate(1,9), Coordinate(2,9), Coordinate(3,9), Coordinate(4,9), Coordinate(5,9),
    Coordinate(0,8), Coordinate(1,8), Coordinate(2,8), Coordinate(3,8), Coordinate(4,8), Coordinate(5,8),
    Coordinate(0,7), Coordinate(1,7), Coordinate(2,7), Coordinate(3,7), Coordinate(4,7), Coordinate(5,7),
    Coordinate(0,6), Coordinate(1,6), Coordinate(2,6), Coordinate(3,6), Coordinate(4,6), Coordinate(5,6),
    Coordinate(0,5), Coordinate(1,5), Coordinate(2,5), Coordinate(3,5), Coordinate(4,5), Coordinate(5,5),
    Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(5,4),
    Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(5,3),
    Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(5,2),
    Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(5,1),
    Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0), Coordinate(5,0)],
  "S" : [Coordinate(0,9), Coordinate(1,9), Coordinate(2,9), Coordinate(3,9), Coordinate(4,9), Coordinate(5,9),
    Coordinate(0,8), Coordinate(1,8), Coordinate(2,8), Coordinate(3,8), Coordinate(4,8), Coordinate(5,8),
    Coordinate(0,7), Coordinate(1,7), Coordinate(2,7), Coordinate(3,7), Coordinate(4,7), Coordinate(5,7),
    Coordinate(0,6), Coordinate(1,6), Coordinate(2,6), Coordinate(3,6), Coordinate(4,6), Coordinate(5,6),
    Coordinate(0,5), Coordinate(1,5), Coordinate(2,5), Coordinate(3,5), Coordinate(4,5), Coordinate(5,5),
    Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(5,4),
    Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(5,3),
    Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(5,2),
    Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(5,1),
    Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0), Coordinate(5,0)],
  "T" : [Coordinate(0,9), Coordinate(1,9), Coordinate(2,9), Coordinate(3,9), Coordinate(4,9), Coordinate(5,9),
    Coordinate(0,8), Coordinate(1,8), Coordinate(2,8), Coordinate(3,8), Coordinate(4,8), Coordinate(5,8),
    Coordinate(0,7), Coordinate(1,7), Coordinate(2,7), Coordinate(3,7), Coordinate(4,7), Coordinate(5,7),
    Coordinate(0,6), Coordinate(1,6), Coordinate(2,6), Coordinate(3,6), Coordinate(4,6), Coordinate(5,6),
    Coordinate(0,5), Coordinate(1,5), Coordinate(2,5), Coordinate(3,5), Coordinate(4,5), Coordinate(5,5),
    Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(5,4),
    Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(5,3),
    Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(5,2),
    Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(5,1),
    Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0), Coordinate(5,0)],
  "U" : [Coordinate(0,9), Coordinate(1,9), Coordinate(2,9), Coordinate(3,9), Coordinate(4,9), Coordinate(5,9),
    Coordinate(0,8), Coordinate(1,8), Coordinate(2,8), Coordinate(3,8), Coordinate(4,8), Coordinate(5,8),
    Coordinate(0,7), Coordinate(1,7), Coordinate(2,7), Coordinate(3,7), Coordinate(4,7), Coordinate(5,7),
    Coordinate(0,6), Coordinate(1,6), Coordinate(2,6), Coordinate(3,6), Coordinate(4,6), Coordinate(5,6),
    Coordinate(0,5), Coordinate(1,5), Coordinate(2,5), Coordinate(3,5), Coordinate(4,5), Coordinate(5,5),
    Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(5,4),
    Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(5,3),
    Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(5,2),
    Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(5,1),
    Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0), Coordinate(5,0)],
  "V" : [Coordinate(0,9), Coordinate(1,9), Coordinate(2,9), Coordinate(3,9), Coordinate(4,9), Coordinate(5,9), Coordinate(6,9),
    Coordinate(0,8), Coordinate(1,8), Coordinate(2,8), Coordinate(3,8), Coordinate(4,8), Coordinate(5,8), Coordinate(6,8),
    Coordinate(0,7), Coordinate(1,7), Coordinate(2,7), Coordinate(3,7), Coordinate(4,7), Coordinate(5,7), Coordinate(6,7),
    Coordinate(0,6), Coordinate(1,6), Coordinate(2,6), Coordinate(3,6), Coordinate(4,6), Coordinate(5,6), Coordinate(6,6),
    Coordinate(0,5), Coordinate(1,5), Coordinate(2,5), Coordinate(3,5), Coordinate(4,5), Coordinate(5,5), Coordinate(6,5),
    Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(5,4), Coordinate(6,4),
    Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(5,3), Coordinate(6,3),
    Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(5,2), Coordinate(6,2),
    Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(5,1), Coordinate(6,1),
    Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0), Coordinate(5,0), Coordinate(6,0),],
  "W" : [Coordinate(0,9), Coordinate(1,9), Coordinate(2,9), Coordinate(3,9), Coordinate(4,9), Coordinate(5,9), Coordinate(6,9),
    Coordinate(0,8), Coordinate(1,8), Coordinate(2,8), Coordinate(3,8), Coordinate(4,8), Coordinate(5,8), Coordinate(6,8),
    Coordinate(0,7), Coordinate(1,7), Coordinate(2,7), Coordinate(3,7), Coordinate(4,7), Coordinate(5,7), Coordinate(6,7),
    Coordinate(0,6), Coordinate(1,6), Coordinate(2,6), Coordinate(3,6), Coordinate(4,6), Coordinate(5,6), Coordinate(6,6),
    Coordinate(0,5), Coordinate(1,5), Coordinate(2,5), Coordinate(3,5), Coordinate(4,5), Coordinate(5,5), Coordinate(6,5),
    Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(5,4), Coordinate(6,4),
    Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(5,3), Coordinate(6,3),
    Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(5,2), Coordinate(6,2),
    Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(5,1), Coordinate(6,1),
    Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0), Coordinate(5,0), Coordinate(6,0),],
  "X" : [Coordinate(0,9), Coordinate(1,9), Coordinate(2,9), Coordinate(3,9), Coordinate(4,9), Coordinate(5,9),
    Coordinate(0,8), Coordinate(1,8), Coordinate(2,8), Coordinate(3,8), Coordinate(4,8), Coordinate(5,8),
    Coordinate(0,7), Coordinate(1,7), Coordinate(2,7), Coordinate(3,7), Coordinate(4,7), Coordinate(5,7),
    Coordinate(0,6), Coordinate(1,6), Coordinate(2,6), Coordinate(3,6), Coordinate(4,6), Coordinate(5,6),
    Coordinate(0,5), Coordinate(1,5), Coordinate(2,5), Coordinate(3,5), Coordinate(4,5), Coordinate(5,5),
    Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(5,4),
    Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(5,3),
    Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(5,2),
    Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(5,1),
    Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0), Coordinate(5,0)],
  "Y" : [Coordinate(0,9), Coordinate(1,9), Coordinate(2,9), Coordinate(3,9), Coordinate(4,9), Coordinate(5,9),
    Coordinate(0,8), Coordinate(1,8), Coordinate(2,8), Coordinate(3,8), Coordinate(4,8), Coordinate(5,8),
    Coordinate(0,7), Coordinate(1,7), Coordinate(2,7), Coordinate(3,7), Coordinate(4,7), Coordinate(5,7),
    Coordinate(0,6), Coordinate(1,6), Coordinate(2,6), Coordinate(3,6), Coordinate(4,6), Coordinate(5,6),
    Coordinate(0,5), Coordinate(1,5), Coordinate(2,5), Coordinate(3,5), Coordinate(4,5), Coordinate(5,5),
    Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(5,4),
    Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(5,3),
    Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(5,2),
    Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(5,1),
    Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0), Coordinate(5,0)],
  "Z" : [Coordinate(0,9), Coordinate(1,9), Coordinate(2,9), Coordinate(3,9), Coordinate(4,9), Coordinate(5,9),
    Coordinate(0,8), Coordinate(1,8), Coordinate(2,8), Coordinate(3,8), Coordinate(4,8), Coordinate(5,8),
    Coordinate(0,7), Coordinate(1,7), Coordinate(2,7), Coordinate(3,7), Coordinate(4,7), Coordinate(5,7),
    Coordinate(0,6), Coordinate(1,6), Coordinate(2,6), Coordinate(3,6), Coordinate(4,6), Coordinate(5,6),
    Coordinate(0,5), Coordinate(1,5), Coordinate(2,5), Coordinate(3,5), Coordinate(4,5), Coordinate(5,5),
    Coordinate(0,4), Coordinate(1,4), Coordinate(2,4), Coordinate(3,4), Coordinate(4,4), Coordinate(5,4),
    Coordinate(0,3), Coordinate(1,3), Coordinate(2,3), Coordinate(3,3), Coordinate(4,3), Coordinate(5,3),
    Coordinate(0,2), Coordinate(1,2), Coordinate(2,2), Coordinate(3,2), Coordinate(4,2), Coordinate(5,2),
    Coordinate(0,1), Coordinate(1,1), Coordinate(2,1), Coordinate(3,1), Coordinate(4,1), Coordinate(5,1),
    Coordinate(0,0), Coordinate(1,0), Coordinate(2,0), Coordinate(3,0), Coordinate(4,0), Coordinate(5,0)],

  " " : [Coordinate(0,0)],

  ":" : [Coordinate(0,0), Coordinate(1,0), Coordinate(2,0)]
};

Map<String, List<Color>> alphabetColors = {

  "0" : [color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"], color["dark"]],
  "1" : [color["dark"], color["dark"], color["dark"], color["dark"], color["dark"]],
  "2" : [color["dark"], color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"], color["dark"]],
  "3" : [color["dark"], color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"], color["dark"], color["dark"]],
  "4" : [color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["light"], color["light"], color["dark"]],
  "5" : [color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"], color["dark"], color["dark"]],
  "6" : [color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"], color["dark"]],
  "7" : [color["dark"], color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["light"], color["dark"], color["light"], color["dark"], color["light"], color["light"], color["dark"], color["light"], color["light"]],
  "8" : [color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"], color["dark"]],
  "9" : [color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"], color["dark"], color["dark"]],

  "a" : [color["light"], color["dark"], color["light"], color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["dark"]],
  "b" : [color["dark"], color["dark"], color["light"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"], color["light"]],
  "c" : [color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["light"], color["light"], color["dark"], color["light"], color["light"], color["dark"], color["dark"], color["dark"]],
  "d" : [color["dark"], color["dark"], color["light"], color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"], color["light"]],
  "e" : [color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["light"], color["light"], color["dark"], color["dark"], color["dark"]],
  "f" : [color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["light"], color["light"], color["dark"], color["light"], color["light"]],
  "g" : [color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["light"], color["light"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"], color["dark"]],
  "h" : [color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["dark"]],
  "i" : [color["dark"], color["dark"], color["dark"], color["light"], color["dark"], color["light"], color["light"], color["dark"], color["light"], color["light"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"]],
  "j" : [color["light"], color["light"], color["dark"], color["light"], color["light"], color["dark"], color["light"], color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"], color["dark"]],
  "k" : [color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"], color["light"], color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["dark"]],
  "l" : [color["dark"], color["light"], color["light"], color["dark"], color["light"], color["light"], color["dark"], color["light"], color["light"], color["dark"], color["light"], color["light"], color["dark"], color["dark"], color["dark"]],
  "m" : [color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"], color["light"], color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"]],
  "n" : [color["dark"], color["light"], color["light"], color["dark"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"], color["dark"]],
  "o" : [color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"], color["dark"]],
  "p" : [color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["light"], color["light"]],
  "q" : [color["light"], color["dark"], color["light"], color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"]],
  "r" : [color["dark"], color["dark"], color["light"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"], color["light"], color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["dark"]],
  "s" : [color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"], color["dark"], color["dark"]],
  "t" : [color["dark"], color["dark"], color["dark"], color["light"], color["dark"], color["light"], color["light"], color["dark"], color["light"], color["light"], color["dark"], color["light"], color["light"], color["dark"], color["light"]],
  "u" : [color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"], color["dark"]],
  "v" : [color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["light"], color["dark"], color["light"]],
  "w" : [color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["light"], color["dark"], color["light"], color["dark"], color["light"], color["dark"], color["light"]],
  "x" : [color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["dark"]],
  "y" : [color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["light"], color["dark"], color["light"], color["light"], color["dark"], color["light"]],
  "z" : [color["dark"], color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["light"], color["dark"], color["light"], color["dark"], color["light"], color["light"], color["dark"], color["dark"], color["dark"]],

  "A" : [color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"],
    color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"]],

  "B" : [color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"]],

  "C" : [color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"]],

  "D" : [color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"]],

  "E" : [color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["light"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"]],

  "F" : [color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["light"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"]],

  "G" : [color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"]],

  "H" : [color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"]],

  "I" : [color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"],
    color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"],
    color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"],
    color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"],
    color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"],
    color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"]],

  "J" : [color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["light"], color["light"], color["light"], color["dark"], color["dark"], color["light"],
    color["light"], color["light"], color["light"], color["dark"], color["dark"], color["light"],
    color["light"], color["light"], color["light"], color["dark"], color["dark"], color["light"],
    color["light"], color["light"], color["light"], color["dark"], color["dark"], color["light"],
    color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["light"],
    color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["light"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"],
    color["light"], color["dark"], color["dark"], color["dark"], color["light"], color["light"]],

  "K" : [color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["light"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["light"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["light"],
    color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"]],

  "L" : [color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"]],

  "M" : [color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["dark"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"]],

  "N" : [color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"]],

  "O" : [color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"]],

  "P" : [color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"]],

  "Q" : [color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"]],

  "R" : [color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"]],

  "S" : [color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"],
    color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["light"], color["light"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"]],

  "T" : [color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"],
    color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"],
    color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"],
    color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"],
    color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"],
    color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"],
    color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"],
    color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"]],

  "U" : [color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"]],

  "V" : [color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"],
    color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["light"],
    color["light"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["light"],
    color["light"], color["light"], color["dark"], color["dark"], color["dark"], color["light"], color["light"],
    color["light"], color["light"], color["dark"], color["dark"], color["dark"], color["light"], color["light"],
    color["light"], color["light"], color["light"], color["dark"], color["light"], color["light"], color["light"]],

  "W" : [color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["dark"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["light"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["dark"], color["dark"]],

  "X" : [color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"],
    color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"],
    color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"]],

  "Y" : [color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["light"], color["light"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["light"], color["dark"], color["dark"], color["dark"], color["dark"], color["light"],
    color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"],
    color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"],
    color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"],
    color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"],
    color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"]],

  "Z" : [color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["light"], color["light"], color["light"], color["light"], color["dark"], color["dark"],
    color["light"], color["light"], color["light"], color["dark"], color["dark"], color["light"],
    color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"],
    color["light"], color["light"], color["dark"], color["dark"], color["light"], color["light"],
    color["light"], color["dark"], color["dark"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["light"], color["light"], color["light"], color["light"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"],
    color["dark"], color["dark"], color["dark"], color["dark"], color["dark"], color["dark"]],

  " " : [color["light"]],

  ":" : [color["dark"], color["light"], color["dark"]]
};

Map<String, int> alphabetWidth = {

  "0" : 3,
  "1" : 1,
  "2" : 3,
  "3" : 3,
  "4" : 3,
  "5" : 3,
  "6" : 3,
  "7" : 3,
  "8" : 3,
  "9" : 3,

  "a" : 3,
  "b" : 3,
  "c" : 3,
  "d" : 3,
  "e" : 3,
  "f" : 3,
  "g" : 3,
  "h" : 3,
  "i" : 3,
  "j" : 3,
  "k" : 3,
  "l" : 3,
  "m" : 5,
  "n" : 4,
  "o" : 3,
  "p" : 3,
  "q" : 4,
  "r" : 3,
  "s" : 3,
  "t" : 3,
  "u" : 3,
  "v" : 3,
  "w" : 5,
  "x" : 3,
  "y" : 3,
  "z" : 3,

  "A" : 6,
  "B" : 6,
  "C" : 6,
  "D" : 6,
  "E" : 6,
  "F" : 6,
  "G" : 6,
  "H" : 6,
  "I" : 6,
  "J" : 6,
  "K" : 6,
  "L" : 6,
  "M" : 7,
  "N" : 7,
  "O" : 6,
  "P" : 6,
  "Q" : 7,
  "R" : 6,
  "S" : 6,
  "T" : 6,
  "U" : 6,
  "V" : 7,
  "W" : 7,
  "X" : 6,
  "Y" : 6,
  "Z" : 6,

  " " : 1,

  ":" : 1
};